version: '3.7'

networks:
  con_mongodb_api:
    driver: bridge
    ipam:
      config:
        - subnet: 172.14.0.0/16
          gateway: 172.14.0.1

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      con_mongodb_api:
        ipv4_address: 172.14.0.10
  api_container:
    image: megakuul/gehege:latest
    environment:
      PORT: 6004
      DB_HOST: 172.14.0.10
      DB_PORT: 27017
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_DATABASE: gehege
      GEHEGE_ADMIN: admin
      GEHEGE_ADMIN_PW: adminpassword
    ports:
      - 6004:6004
    networks:
      con_mongodb_api:
        ipv4_address: 172.14.0.20