apiVersion: v1
kind: Namespace
metadata:
  name: gehege
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gehege
  name: gehege-backend
spec:
  selector:
    matchLabels:
      app: gehege-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: gehege-backend
    spec:
      containers:
      - name: gehege-backend
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        image: megakuul/gehege:latest
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: DB_HOST
          value: "DBHostname"
        - name: DB_PORT
          value: "27017"
        - name: DB_USER
          value: "DBUser"
        - name: DB_PASSWORD
          value: "DBPassword"
        - name: DB_DATABASE
          value: "gehege"
        - name: GEHEGE_ADMIN
          value: "dashboardadmin"
        - name: GEHEGE_ADMIN_PW
          value: "dashboardadminpassword" 
        - name: DB_USEHOSTNAME
          value: "true"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gehege-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gehege-backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gehege-lb
  namespace: gehege
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: gehege-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80